import { DEFAULT_PREFS } from "../policy";
import type {
  AccountKind,
  Database,
  Niche,
  Participation,
  ParticipationRole,
  ParticipationStatus,
  Prefs,
  UserRecord,
} from "../types";
import { hashPassword } from "./password";

function ago(hours: number) {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
}

type SeedUser = {
  handle: string;
  name: string;
  bio: string;
  tags: string[];
  kind: AccountKind;
  initials: string;
  prefs: Partial<Prefs>;
  city?: string;
  available?: boolean;
  role?: UserRecord["role"];
  niches?: Niche[];
  password?: string;
};

function user(seed: SeedUser): UserRecord {
  return {
    id: `u-${seed.handle}`,
    handle: seed.handle,
    name: seed.name,
    bio: seed.bio,
    tags: seed.tags,
    avatarInitials: seed.initials,
    available: seed.available ?? true,
    role: seed.role ?? "member",
    kind: seed.kind,
    city: seed.city ?? "Vitória, ES",
    links: [],
    avatarId: null,
    coverId: null,
    prefs: { ...DEFAULT_PREFS, ...seed.prefs },
    niches: seed.niches ?? [],
    edital: null,
    createdAt: ago(24 * 40),
    limited: false,
    passwordHash: hashPassword(seed.password ?? "cultura123"),
  };
}

function took(
  id: string,
  userHandle: string,
  niche: Niche,
  role: ParticipationRole,
  eventTitle: string,
  date: string,
  city: string,
  status: ParticipationStatus,
  organizerHandle: string | null = null
): Participation {
  return {
    id,
    userHandle,
    niche,
    role,
    eventId: null,
    eventTitle,
    date,
    city,
    organizerHandle,
    status,
    note: "",
    createdAt: ago(24 * 20),
    decidedAt: status === "confirmada" ? ago(24 * 19) : null,
  };
}

export function seedParticipations(): Participation[] {
  return [
    took("pa1", "mckalil", "mc", "campeao", "Batalha do Centro — edição 41", "2026-06-14", "Vitória, ES", "confirmada", "valecultural"),
    took("pa2", "mckalil", "mc", "finalista", "Batalha do Centro — edição 39", "2026-04-12", "Vitória, ES", "confirmada", "valecultural"),
    took("pa3", "mckalil", "mc", "vice", "Seletiva estadual de MCs", "2025-11-08", "Serra, ES", "declarada"),
    took("pa4", "mckalil", "mc", "competidor", "Batalha da Aldeia", "2025-08-20", "Barueri, SP", "declarada"),
    took("pa5", "mckalil", "mc", "atracao", "Festival Urban Pulse 2025", "2025-10-12", "Vitória, ES", "confirmada", "valecultural"),
    took("pa6", "mckalil", "breaking", "competidor", "Cypher do Moscoso", "2026-03-01", "Vitória, ES", "declarada"),
    took("pa7", "mckalil", "graffiti", "atracao", "Mutirão de graffiti de Jaburuna", "2026-05-10", "Vila Velha, ES", "declarada"),
    took("pa8", "mckalil", "educacao", "oficina", "Oficina de rima nas escolas", "2026-07-22", "Cariacica, ES", "confirmada", "valecultural"),
    took("pa9", "mckalil", "mc", "jurado", "Batalha da Serra", "2026-08-03", "Serra, ES", "declarada"),
    took("pa10", "djrima", "dj", "atracao", "Batalha do Centro — edição 41", "2026-06-14", "Vitória, ES", "confirmada", "valecultural"),
    took("pa11", "djrima", "dj", "atracao", "Festival Urban Pulse 2025", "2025-10-12", "Vitória, ES", "confirmada", "valecultural"),
    took("pa12", "djrima", "dj", "campeao", "Batalha de DJs Capixaba", "2026-02-15", "Vila Velha, ES", "declarada"),
    took("pa13", "djrima", "beatmaker", "producao", "Trilha oficial da Batalha do Centro", "2026-06-14", "Vitória, ES", "confirmada", "valecultural"),
    took("pa14", "slamvix", "realizacao", "organizacao", "Slam da Praça — edição 20", "2026-08-15", "Vila Velha, ES", "declarada"),
    took("pa15", "slamvix", "poesia", "finalista", "Slam BR — etapa nacional", "2025-12-05", "Rio de Janeiro, RJ", "declarada"),
    took("pa16", "slamvix", "poesia", "campeao", "Slam ES", "2026-05-02", "Vitória, ES", "declarada"),
    took("pa17", "slamvix", "poesia", "atracao", "Festival Urban Pulse 2025", "2025-10-12", "Vitória, ES", "pendente", "valecultural"),
    took("pa18", "valecultural", "realizacao", "organizacao", "Festival Urban Pulse 2025", "2025-10-12", "Vitória, ES", "declarada"),
    took("pa19", "valecultural", "realizacao", "organizacao", "Batalha do Centro — edição 39", "2026-04-12", "Vitória, ES", "declarada"),
    took("pa20", "valecultural", "realizacao", "organizacao", "Batalha do Centro — edição 41", "2026-06-14", "Vitória, ES", "declarada"),
    took("pa21", "rimaforte", "audiovisual", "producao", "Registro em vídeo do Cypher do Moscoso", "2026-03-01", "Vitória, ES", "declarada"),
  ];
}

export function createSeed(): Database {
  return {
    version: 4,
    users: [
      user({
        handle: "mckalil",
        name: "MC Kalil",
        bio: "Artista da cena urbana capixaba. Rima, dança e graffiti desde 2015. Transformando vivência em arte.",
        tags: ["MC", "DJ", "Breaking", "Graffiti", "Slam"],
        kind: "artista",
        initials: "MK",
        niches: ["mc", "breaking", "graffiti", "educacao"],
        prefs: { accent: "#ff5a1f", accent2: "#ec2f77", shape: "triangulo" },
      }),
      user({
        handle: "djrima",
        name: "DJ Rima",
        bio: "Discotecagem e produção musical para batalhas de MC e festas de rua no Espírito Santo.",
        tags: ["DJ", "Set", "MC"],
        kind: "artista",
        initials: "DR",
        city: "Vila Velha, ES",
        niches: ["dj", "beatmaker", "producao"],
        prefs: { accent: "#8b5cf6", accent2: "#22d3ee", shape: "hexagono" },
      }),
      user({
        handle: "slamvix",
        name: "Slam Vitória",
        bio: "Coletivo de poesia falada da Grande Vitória. Levamos slam para escolas, praças e teatros.",
        tags: ["Slam", "Poesia"],
        kind: "artista",
        initials: "SV",
        available: false,
        niches: ["poesia", "realizacao"],
        prefs: { accent: "#10b981", accent2: "#f59e0b", shape: "losango" },
      }),
      user({
        handle: "valecultural",
        name: "Produtora Vale Cultural",
        bio: "Festivais e batalhas culturais na Grande Vitória há 6 anos. Line-ups abertos para artistas da rede.",
        tags: ["Festival", "MC", "Breaking", "DJ"],
        kind: "produtora",
        initials: "VC",
        niches: ["realizacao"],
        prefs: { accent: "#f59e0b", accent2: "#ef4444", shape: "circulo" },
      }),
      user({
        handle: "rimaforte",
        name: "Estúdio Rima Forte",
        bio: "Estúdio de gravação e ensaio em Vitória. Condição especial para artistas da Cultura Conecta.",
        tags: ["Gravação", "Slam", "MC", "Poesia"],
        kind: "estudio",
        initials: "RF",
        niches: ["producao", "audiovisual"],
        prefs: { accent: "#06b6d4", accent2: "#6366f1", shape: "hexagono" },
      }),
      user({
        handle: "equipe",
        name: "Equipe Cultura Conecta",
        bio: "Conta da equipe. Analisa denúncias e cuida das regras da comunidade.",
        tags: ["Moderação"],
        kind: "publico",
        initials: "EQ",
        role: "moderator",
        available: false,
        password: "modera123",
        prefs: { shape: "triangulo" },
      }),
    ],
    posts: [
      {
        id: "p1",
        authorHandle: "mckalil",
        category: "Graffiti",
        text: "Nova collab de graffiti no centro de Vitória saindo neste final de semana. Quem for da cena, aparece com respeito e tinta.",
        imageId: null,
        feat: null,
        featStatus: null,
        music: null,
        createdAt: ago(2),
        hidden: false,
      },
      {
        id: "p5",
        authorHandle: "djrima",
        category: "Set",
        text: "Beat novo fechado a quatro mãos. A letra ficou por conta dele, o grave por minha conta. Sai sexta.",
        imageId: null,
        feat: "mckalil",
        featStatus: "aceito",
        music: null,
        createdAt: ago(4),
        hidden: false,
      },
      {
        id: "p2",
        authorHandle: "mckalil",
        category: "Breaking",
        text: "Registro do cypher no Parque Moscoso. Sintonia máxima com a galera do breaking. Sábado que vem tem mais.",
        imageId: null,
        feat: null,
        featStatus: null,
        music: null,
        createdAt: ago(26),
        hidden: false,
      },
      {
        id: "p3",
        authorHandle: "djrima",
        category: "Set",
        text: "Set novo gravado ao vivo na batalha de sábado. Se for usar em evento, chama na mensagem.",
        imageId: null,
        feat: null,
        featStatus: null,
        music: null,
        createdAt: ago(5),
        hidden: false,
      },
      {
        id: "p4",
        authorHandle: "slamvix",
        category: "Slam",
        text: "Inscrições abertas para o próximo slam na Praça dos Namorados. Poetas da Grande Vitória, bora.",
        imageId: null,
        feat: null,
        featStatus: null,
        music: null,
        createdAt: ago(48),
        hidden: false,
      },
      {
        id: "p6",
        authorHandle: "valecultural",
        category: "Evento",
        text: "O Urban Pulse volta ao Parque Moscoso em outubro. Line-up aberto no mural de oportunidades: MC, breaking e DJ.",
        imageId: null,
        feat: null,
        featStatus: null,
        music: null,
        createdAt: ago(8),
        hidden: false,
      },
    ],
    comments: [
      {
        id: "c1",
        postId: "p1",
        authorHandle: "djrima",
        text: "Levo a caixa. Só confirma o horário que eu fecho o set.",
        createdAt: ago(1),
        hidden: false,
      },
    ],
    reactions: [
      { postId: "p1", userHandle: "djrima", type: "like" },
      { postId: "p1", userHandle: "slamvix", type: "fire" },
      { postId: "p2", userHandle: "djrima", type: "fire" },
      { postId: "p3", userHandle: "mckalil", type: "like" },
      { postId: "p4", userHandle: "mckalil", type: "arrepio" },
      { postId: "p5", userHandle: "slamvix", type: "fire" },
      { postId: "p5", userHandle: "valecultural", type: "like" },
      { postId: "p6", userHandle: "mckalil", type: "like" },
    ],
    reposts: [{ postId: "p4", userHandle: "mckalil", createdAt: ago(20) }],
    follows: [
      { follower: "mckalil", following: "djrima" },
      { follower: "mckalil", following: "slamvix" },
      { follower: "djrima", following: "mckalil" },
      { follower: "slamvix", following: "mckalil" },
      { follower: "djrima", following: "slamvix" },
      { follower: "valecultural", following: "mckalil" },
      { follower: "rimaforte", following: "slamvix" },
    ],
    notifications: [
      {
        id: "n-pa17",
        userHandle: "valecultural",
        type: "participation",
        actorHandle: "slamvix",
        text: "pediu que você confirme a participação em “Festival Urban Pulse 2025” (Poesia e slam · Atração ou show).",
        href: "/perfil/slamvix#conquistas",
        targetId: "pa17",
        createdAt: ago(24 * 20),
        read: false,
      },
    ],
    messages: [
      {
        id: "m1",
        fromHandle: "djrima",
        toHandle: "mckalil",
        text: "Kalil, o set de sábado está pronto. Quer ouvir antes da batalha?",
        createdAt: ago(6),
        hidden: false,
      },
    ],
    reports: [],
    blocks: [],
    rsvps: [
      { eventId: "e1", userHandle: "djrima" },
      { eventId: "e1", userHandle: "slamvix" },
    ],
    sessions: [],
    events: [
      {
        id: "e1",
        title: "Batalha do Centro — MC's",
        date: "Sáb, 4 out · 19h",
        startsAt: null,
        location: "Praça Costa Pereira, Vitória",
        category: "Batalha",
        free: true,
        artistHandles: ["mckalil", "djrima"],
        createdBy: null,
        description: "",
      },
      {
        id: "e2",
        title: "Festival Urban Pulse",
        date: "Dom, 12 out · 14h",
        startsAt: null,
        location: "Parque Moscoso, Vitória",
        category: "Festival",
        free: false,
        price: "R$ 20",
        artistHandles: ["mckalil"],
        createdBy: "valecultural",
        description: "",
      },
      {
        id: "e3",
        title: "Slam da Praça",
        date: "Sex, 17 out · 19h30",
        startsAt: null,
        location: "Praça dos Namorados, Vila Velha",
        category: "Slam",
        free: true,
        artistHandles: ["slamvix"],
        createdBy: null,
        description: "",
      },
      {
        id: "e4",
        title: "Cypher de Breaking + DJ set",
        date: "Sáb, 25 out · 18h",
        startsAt: null,
        location: "Convés Cultural, Vitória",
        category: "Breaking",
        free: true,
        artistHandles: ["mckalil", "djrima"],
        createdBy: null,
        description: "",
      },
    ],
    sponsors: [
      {
        id: "s1",
        name: "Produtora Vale Cultural",
        category: "Produtora de eventos",
        description: "Realiza festivais e batalhas culturais na Grande Vitória há 6 anos.",
        projectsSupported: 12,
      },
      {
        id: "s2",
        name: "Estúdio Rima Forte",
        category: "Estúdio de gravação",
        description: "Estúdio parceiro, com condição especial de gravação para artistas da rede.",
        projectsSupported: 4,
      },
      {
        id: "s3",
        name: "Prefeitura de Vitória — Cultura",
        category: "Órgão público",
        description: "Apoia editais e temporadas de programação cultural no município.",
        projectsSupported: 20,
      },
    ],
    testimonials: [
      {
        id: "t1",
        artistHandle: "mckalil",
        author: "Produtora Vale Cultural",
        authorHandle: "valecultural",
        text: "Trabalhamos com o Kalil em três edições do festival. Presença de palco firme e respeito com a equipe.",
        createdAt: ago(24 * 10),
      },
      {
        id: "t2",
        artistHandle: "mckalil",
        author: "DJ Rima",
        authorHandle: "djrima",
        text: "Parceiro de cypher desde 2019. O flow segura a roda inteira.",
        createdAt: ago(24 * 5),
      },
      {
        id: "t3",
        artistHandle: "djrima",
        author: "MC Kalil",
        authorHandle: "mckalil",
        text: "O beat da Rima é quem levanta o cypher.",
        createdAt: ago(24 * 3),
      },
    ],
    stories: [
      {
        id: "st1",
        authorHandle: "valecultural",
        text: "Line-up do Urban Pulse sai sexta. Fica de olho no mural.",
        imageId: null,
        bg: "ouro",
        createdAt: ago(1),
        hidden: false,
      },
      {
        id: "st2",
        authorHandle: "mckalil",
        text: "Hoje tem cypher no Moscoso às 18h. Traga sua rima.",
        imageId: null,
        bg: "brasa",
        createdAt: ago(3),
        hidden: false,
      },
      {
        id: "st3",
        authorHandle: "slamvix",
        text: "Tema do próximo slam: território.",
        imageId: null,
        bg: "mata",
        createdAt: ago(5),
        hidden: false,
      },
      {
        id: "st4",
        authorHandle: "djrima",
        text: "Caixa montada. Hoje o grave vem pesado.",
        imageId: null,
        bg: "noite",
        createdAt: ago(2),
        hidden: false,
      },
    ],
    opportunities: [
      {
        id: "o1",
        authorHandle: "valecultural",
        type: "show",
        title: "Line-up do Festival Urban Pulse",
        description: "Procuramos 4 atrações locais para o palco da tarde: MC, breaking e DJ. Passagem de som às 12h. Mande um trecho do seu trabalho na candidatura.",
        city: "Vitória, ES",
        date: "12 out",
        fee: "R$ 800 + transporte",
        tags: ["MC", "Breaking", "DJ"],
        createdAt: ago(8),
        open: true,
        hidden: false,
      },
      {
        id: "o2",
        authorHandle: "rimaforte",
        type: "gravacao",
        title: "Gravação gratuita para 3 artistas de slam",
        description: "Três poetas selecionados gravam um poema em áudio e vídeo no estúdio, sem custo. O material é seu para divulgar.",
        city: "Vitória, ES",
        date: "Até 30 out",
        fee: "Sem custo",
        tags: ["Slam", "Poesia"],
        createdAt: ago(20),
        open: true,
        hidden: false,
      },
      {
        id: "o3",
        authorHandle: "valecultural",
        type: "edital",
        title: "Oficinas de graffiti em escolas",
        description: "Seis oficinas de 2 horas em escolas estaduais da Grande Vitória. Material fornecido pela produção.",
        city: "Grande Vitória, ES",
        date: "Nov e dez",
        fee: "R$ 350 por oficina",
        tags: ["Graffiti"],
        createdAt: ago(30),
        open: true,
        hidden: false,
      },
    ],
    applications: [
      {
        id: "a1",
        opportunityId: "o1",
        applicantHandle: "djrima",
        pitch: "Set de 40 minutos com beats autorais, pronto para acompanhar MC ao vivo.",
        createdAt: ago(6),
        status: "enviada",
      },
    ],
    participations: seedParticipations(),
    jams: [],
    jamMembers: [],
    media: [],
  };
}
